#!/usr/bin/python3

import os
import shutil
import json

# Helper functions
def prompt_yes_no(msg, automatic_yes=False, ask_twice=False):

    assert type(automatic_yes) is bool
    assert type(ask_twice) is bool

    if automatic_yes:
        return True
    else: 
        YES_ANSWERS = ['y', 'Y']
        if ask_twice:
            return (input(msg + " [yY/nN]: ") in YES_ANSWERS and
                input("Are you sure? [yY/nN]: ") in YES_ANSWERS)
        else:
            return input(msg + " [yY/nN]: ") in YES_ANSWERS

def pathlink(settings_path, execute_linking=True, automatic_yes=False):

    assert type(execute_linking) is bool
    assert type(automatic_yes) is bool

    with open(settings_path, 'r') as f:
        settings = json.load(f)

    tracked_paths = settings['tracked_paths']
    original_dir = settings['original_dir']
    destination_dir = settings['destination_dir']

    assert type(tracked_paths) is list, "tracked_paths is not a list"
    assert tracked_paths, "tracked_paths is empty"
    assert isinstance(original_dir, str) and os.path.isdir(original_dir), "original_dir is not a directory"
    assert isinstance(original_dir, str) and os.path.isdir(destination_dir), "destination_dir is not a directory"

    for tracked_path in tracked_paths:

        original_path = os.path.join(original_dir, tracked_path)
        destination_path = os.path.join(destination_dir, tracked_path)

        print(f"### Processing dir {destination_path} ###")

        if os.path.exists(destination_path):
            if not os.path.exists(original_path) and not os.path.islink(original_path):
                if execute_linking and prompt_yes_no("original_dir: Link doesn't exist. Do you want to add?", automatic_yes=automatic_yes):
                    os.symlink(destination_path, original_path)
            elif os.path.islink(original_path):
                if os.readlink(original_path) == destination_path:
                    print(f"original_dir: Symbolic link {original_path} already points to correct location")
                else:
                    if execute_linking and prompt_yes_no(f"original_dir: Symbolic link {original_path} points to other location: {os.readlink(original_path)}. Do you want to overwrite it?"
                            , automatic_yes=automatic_yes, ask_twice=True):
                        os.unlink(original_path)
                        os.symlink(destination_path, original_path)
            elif os.path.isdir(original_path):
                if execute_linking and prompt_yes_no(f"original_dir: Folder {original_path} already exists. Do you want to overwrite it?"
                        , automatic_yes=automatic_yes, ask_twice=True):
                    shutil.rmtree(original_path)
                    os.symlink(destination_path, original_path)
            else: # should be a file
                if execute_linking and prompt_yes_no(f"original_dir: File {original_path} already exists. Do you want to overwrite it?"
                        , automatic_yes=automatic_yes, ask_twice=True):
                    os.remove(original_path)
                    os.symlink(destination_path, original_path)
        else: # backup path doesn't exist
            if not os.path.exists(original_path) and not os.path.islink(original_path):
                print("original and destination paths don't exist.")
            elif os.path.islink(original_path):
                print("original path is a link. no destination path.")
            else: # original path is a file/dir 
                if execute_linking and prompt_yes_no("original_dir: File/folder exists. Do you want to move it to destination and link it?", automatic_yes=automatic_yes):
                    # Move original to backup location
                    backup_path_folder = os.path.abspath(os.path.join(destination_path, '..'))
                    shutil.move(original_path, backup_path_folder)
                    # Create symlink
                    os.symlink(destination_path, original_path)
                else:
                    print("Ok. DIY")
            


if __name__ == "__main__":
    PATHLINKER_JSON = os.path.join(os.path.expanduser('~'), '.pathlinker.json')
    pathlink(PATHLINKER_JSON)

